# Regla para redirigir todas las llamadas de /api/* a nuestra funcion proxy.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Configuracion general para TODAS las funciones.
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Configuración específica para nuestra funcion llamada "api".
# Aqui es donde debemos poner el timeout.
[functions.api]
  timeout = 90