# Regla para redirigir todas las llamadas de /api/* a nuestra funcion proxy.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Configuracion de la funcion (incluyendo el timeout que ya teniamos).
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  timeout = 90